services:
  app:
    networks:
      - devnet
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
    volumes:
      - ./:/var/www/html:ro
      - app_storage:/var/www/html/storage
      - ./docker/php/opcache-dev.ini:/usr/local/etc/php/conf.d/99-opcache.ini:ro
    deploy: null

  scheduler:
    networks:
      - devnet
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
    deploy: null

  worker:
    networks:
      - devnet
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
    deploy: null

networks:
  devnet:
    driver: bridge
  # Sobrescrever network_public para não ser externa em dev
  network_public:
    external: false
    driver: bridge
